Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        'centos_7_8_x64_20G_alibase_20211130.vhd':
          ArtifactId: artifact-xxx
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: ecs image deploy
    Image: 'icons/service_logo.png'
    Name: ECS镜像部署单机版
  ShareType: Public
  ApprovalType: Manual