ROSTemplateFormatVersion: '2015-09-01'
# 定义参数
Parameters:
  Parameters:
    Label:
      en: Customized service parameters
      zh-cn: 自定义服务参数
    Description:
      en: Customized service parameters, can be referenced in command content
      zh-cn: 自定义的服务参数，可以在命令中引用参数
    Type: Json
    AssociationProperty: List[Parameters]
    AssociationPropertyMetadata:
      Parameters:
        Name:
          Type: String
        Label:
          Type: String
        Type:
          Type: String
          AllowedValues:
            - Integer
            - String
            - Boolean
            - Json
        AllowedValues:
          Type: Json
          AssociationProperty: List
          AssociationPropertyMetadata:
            Multiple: true
          Default: Null
          Required: false
        NoEcho:
          Type: Boolean
          Default: false
          AllowedValues:
            - true
            - false
        AssociationProperty:
          Type: String
          Default: Null
          Required: false
          AssociationProperty: AssociationProperty
    Default:
    - Name: AdminPassword
      NoEcho: true
      Type: String
      Label: 管理员密码
      AssociationProperty: ALIYUN::ECS::Instance::Password
  Command:
    Label:
      en: Initialization command
      zh-cn: 初始化命令
    Description:
      en: Initialize your software in command
      zh-cn: 在命令中对软件进行初始化
    Type: String
    AssociationProperty: Code
    Default: |
      #!/bin/bash
      echo ${AdminPassword}
  CommandTimeout:
    Label:
      en: Timeout of command in seconds
      zh-cn: 命令超时时间（秒）
    Type: Number
    Default: 300
  EcsImageArtifactId:
    Type: String
    Label:
      en: ECS image artifact id
      zh-cn: ECS镜像部署物Id
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactId
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactType: EcsImage
  EcsImageArtifactVersion:
    Type: String
    Label:
      en: ECS image artifact version
      zh-cn: ECS镜像部署物版本
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactIdVersion
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactId: ${EcsImageArtifactId}
  Ports:
    Type: Json
    Label:
      en: security group ports
      zh-cn: 安全组开放端口
    AssociationProperty: List
    AssociationPropertyMetadata:
      Multiple: true
    Default:
      - 8080
    Required: true
    MinLength: 1
  InstanceTypes:
    Type: Json
    Label:
      en: ECS instance types
      zh-cn: ECS实例规格列表
    Description:
      en: ECS instance types that user can choose
      zh-cn: 用户可选的ECS实例规格范围
    AssociationProperty: ALIYUN::ECS::Instance::InstanceType
    AssociationPropertyMetadata:
      Multiple: true
    Default:
      - ecs.c6.large
      - ecs.c6.xlarge
      - ecs.c6.2xlarge
  Outputs:
    Label:
      en: Service outputs
      zh-cn: 服务输出
    Description:
      en: Service outputs
      zh-cn: 服务输出，可以引用参数或Address，Address代表公网IP
    Type: Json
    AssociationProperty: List[Parameters]
    AssociationPropertyMetadata:
      Parameters:
        DisplayName:
          Type: String
        Expression:
          Type: String
    Default:
    - DisplayName: Endpoint
      Expression: http://${Address}:8080
Metadata:
  ALIYUN::ROS::Interface:
    # 定义资源分组，创建服务实例时，同一分组的参数分布在一起
    ParameterGroups:
      - Parameters:
          - Label: Ecs镜像部署物
            Items:
              - EcsImageArtifactId
              - EcsImageArtifactVersion
          - Parameters
          - Command
          - CommandTimeout
        Label:
          en: Deployment Configuration
          zh-cn: 软件配置
      - Parameters:
          - InstanceTypes
          - Ports
        Label:
          en: Security Configuration
          zh-cn: 实例配置
      - Parameters:
          - Outputs
        Label:
          en: Deployment Configuration
          zh-cn: 输出配置
